"""bio and profile pic fields updated to User model

Revision ID: 85cfb1f06abf
Revises: 3713421f1a64
Create Date: 2019-04-29 15:30:55.478570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85cfb1f06abf'
down_revision = '3713421f1a64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('prof_pic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'prof_pic')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
